/*
 * Super Resolution
 * Copyright (c) 2026. 187J3X1-114514
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

package io.homo.superresolution.core.graphics.d3d12;

#if MC_VER >= MC_1_20_1 && MC_VER < MC_26_2
import io.homo.superresolution.common.upscale.InteropResourcesConverter;
import io.homo.superresolution.core.NativeLibManager;
import io.homo.superresolution.core.graphics.impl.texture.ITexture;
import io.homo.superresolution.core.graphics.impl.texture.TextureDescription;
import io.homo.superresolution.core.graphics.impl.texture.TextureFormat;
import io.homo.superresolution.core.graphics.impl.texture.TextureType;
import io.homo.superresolution.core.graphics.impl.texture.TextureUsages;
import io.homo.superresolution.srapi.SRSurfaceFormat;
import org.lwjgl.opengl.EXTMemoryObject;
import org.lwjgl.opengl.EXTMemoryObjectWin32;
import org.lwjgl.opengl.GL;
import org.lwjgl.system.MemoryStack;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_BYTE;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
import static org.lwjgl.opengl.EXTSemaphore.GL_LAYOUT_GENERAL_EXT;

/**
 * D3D12 presentation via the Java FFM (Foreign Function & Memory API) bindings
 * generated by WindowsApiGenerator. Owns a DXGI flip-model swap chain on the
 * Minecraft window (created GLFW_NO_API, so it carries no OpenGL pixel format),
 * a shared capture texture and a shared timeline fence. The OpenGL side flips
 * the final frame into the capture texture; this context blits it into the swap
 * chain back buffer and presents.
 */
public final class D3D12PresentationContext implements AutoCloseable {
    private final Arena arena;
    private final long hwnd;
    private final MemorySegment device;
    private final MemorySegment queue;
    private MemorySegment swapchain;
    private final MemorySegment commandAllocator;
    private final MemorySegment commandList;
    private final MemorySegment fence;
    private MemorySegment captureTexture;
    private long captureAllocationSize;

    private GlD3D12ImportableTexture2D captureGlTexture;
    private final D3D12InteropSemaphore semaphore;
    private int width;
    private int height;
    private long nextGlFence = 1;
    private long lastD3d12Signal;
    private volatile boolean vsync = true;

    private D3D12PresentationContext(
            Arena arena, long hwnd, MemorySegment device, MemorySegment queue, MemorySegment swapchain,
            MemorySegment commandAllocator, MemorySegment commandList, MemorySegment fence,
            MemorySegment captureTexture, long captureAllocationSize,
            GlD3D12ImportableTexture2D captureGlTexture, D3D12InteropSemaphore semaphore,
            int width, int height) {
        this.arena = arena;
        this.hwnd = hwnd;
        this.device = device;
        this.queue = queue;
        this.swapchain = swapchain;
        this.commandAllocator = commandAllocator;
        this.commandList = commandList;
        this.fence = fence;
        this.captureTexture = captureTexture;
        this.captureAllocationSize = captureAllocationSize;
        this.captureGlTexture = captureGlTexture;
        this.semaphore = semaphore;
        this.width = width;
        this.height = height;
    }

    public static D3D12PresentationContext create(long hwnd, int width, int height) {
        // The hidden GL helper window's capabilities may not carry the memory-object
        // extensions if they were captured on a different context; refresh them now
        // (the render thread current context is the hidden GL window).
        GL.createCapabilities();
        io.homo.superresolution.common.SuperResolution.LOGGER.info(
                "[D3D12] create: current={} renderHandle={} gl={} renderer='{}' ext_mem={} ext_mem_win32={} ext_sem_win32={}",
                org.lwjgl.glfw.GLFW.glfwGetCurrentContext(),
                io.homo.superresolution.common.presentation.window.PresentationWindowState.renderHandle(),
                org.lwjgl.opengl.GL11.glGetString(org.lwjgl.opengl.GL11.GL_VERSION),
                org.lwjgl.opengl.GL11.glGetString(org.lwjgl.opengl.GL11.GL_RENDERER),
                GL.getCapabilities().GL_EXT_memory_object,
                GL.getCapabilities().GL_EXT_memory_object_win32,
                GL.getCapabilities().GL_EXT_semaphore_win32);
        if (!GL.getCapabilities().GL_EXT_memory_object_win32 ||
                !GL.getCapabilities().GL_EXT_semaphore_win32) {
            throw new UnsupportedOperationException(
                    "D3D12 presentation requires GL_EXT_memory_object_win32 and GL_EXT_semaphore_win32.");
        }
        Arena arena = Arena.ofShared();
        try {
            long adapterLuid = queryOpenGlAdapterLuid();

            MemorySegment ppFactory = arena.allocate(ADDRESS);
            checkHr(windows.win32.graphics.dxgi.Apis.CreateDXGIFactory2(
                    0, windows.win32.graphics.dxgi.IDXGIFactory6.iid(), ppFactory));
            windows.win32.graphics.dxgi.IDXGIFactory6 factory =
                    windows.win32.graphics.dxgi.IDXGIFactory6.wrap(ppFactory.get(ADDRESS, 0));

            MemorySegment adapter = findAdapter(factory, arena, adapterLuid);
            if (adapter.address() == 0) {
                throw new IllegalStateException("No D3D12 adapter matches the OpenGL device LUID.");
            }

            MemorySegment ppDevice = arena.allocate(ADDRESS);
            checkHr(windows.win32.graphics.direct3d12.Apis.D3D12CreateDevice(
                    adapter, windows.win32.graphics.direct3d.D3D_FEATURE_LEVEL._12_0,
                    windows.win32.graphics.direct3d12.ID3D12Device.iid(), ppDevice));
            windows.win32.graphics.direct3d12.ID3D12Device device =
                    windows.win32.graphics.direct3d12.ID3D12Device.wrap(ppDevice.get(ADDRESS, 0));
            MemorySegment devicePtr = ppDevice.get(ADDRESS, 0);

            MemorySegment queueDesc = arena.allocate(
                    windows.win32.graphics.direct3d12.D3D12_COMMAND_QUEUE_DESC.layout());
            windows.win32.graphics.direct3d12.D3D12_COMMAND_QUEUE_DESC.Type(
                    queueDesc, windows.win32.graphics.direct3d12.D3D12_COMMAND_LIST_TYPE.DIRECT);
            windows.win32.graphics.direct3d12.D3D12_COMMAND_QUEUE_DESC.Priority(queueDesc, 0);
            windows.win32.graphics.direct3d12.D3D12_COMMAND_QUEUE_DESC.Flags(queueDesc, 0);
            windows.win32.graphics.direct3d12.D3D12_COMMAND_QUEUE_DESC.NodeMask(queueDesc, 0);
            MemorySegment ppQueue = arena.allocate(ADDRESS);
            checkHr(device.CreateCommandQueue(
                    queueDesc, windows.win32.graphics.direct3d12.ID3D12CommandQueue.iid(), ppQueue));
            MemorySegment queuePtr = ppQueue.get(ADDRESS, 0);

            MemorySegment scDesc = buildSwapchainDesc(arena, width, height);
            MemorySegment ppSwapchain = arena.allocate(ADDRESS);
            checkHr(factory.CreateSwapChainForHwnd(
                    queuePtr, MemorySegment.ofAddress(hwnd), scDesc, MemorySegment.NULL,
                    MemorySegment.NULL, ppSwapchain));
            MemorySegment swapchainPtr = ppSwapchain.get(ADDRESS, 0);
            diagnoseSwapchainHook(swapchainPtr);
            diagnoseNativeEntryHooks();

            MemorySegment ppAllocator = arena.allocate(ADDRESS);
            checkHr(device.CreateCommandAllocator(
                    windows.win32.graphics.direct3d12.D3D12_COMMAND_LIST_TYPE.DIRECT,
                    windows.win32.graphics.direct3d12.ID3D12CommandAllocator.iid(), ppAllocator));
            MemorySegment allocatorPtr = ppAllocator.get(ADDRESS, 0);
            MemorySegment ppList = arena.allocate(ADDRESS);
            checkHr(device.CreateCommandList(
                    0, windows.win32.graphics.direct3d12.D3D12_COMMAND_LIST_TYPE.DIRECT,
                    allocatorPtr, MemorySegment.NULL,
                    windows.win32.graphics.direct3d12.ID3D12GraphicsCommandList.iid(), ppList));
            MemorySegment listPtr = ppList.get(ADDRESS, 0);
            checkHr(windows.win32.graphics.direct3d12.ID3D12GraphicsCommandList.wrap(listPtr)
                    .Close());

            MemorySegment ppFence = arena.allocate(ADDRESS);
            checkHr(device.CreateFence(
                    0, windows.win32.graphics.direct3d12.D3D12_FENCE_FLAGS.D3D12_FENCE_FLAG_SHARED,
                    windows.win32.graphics.direct3d12.ID3D12Fence.iid(), ppFence));
            MemorySegment fencePtr = ppFence.get(ADDRESS, 0);
            long fenceHandle = createSharedHandle(arena, device, fencePtr);

            MemorySegment captureDesc = fillResourceDesc(arena, width, height);
            MemorySegment captureTexture = createCaptureTexture(arena, device, captureDesc);
            long captureHandle = createSharedHandle(arena, device, captureTexture);
            long allocationSize = queryAllocationSize(arena, device, captureDesc);

            D3D12InteropSemaphore semaphore = new D3D12InteropSemaphore(fenceHandle);
            D3D12InteropContext.Resource glResource = new D3D12InteropContext.Resource(
                    0, 0, captureHandle, allocationSize,
                    textureDescription(width, height), SRSurfaceFormat.R8G8B8A8_UNORM);
            GlD3D12ImportableTexture2D captureGlTexture =
                    new GlD3D12ImportableTexture2D(glResource);

            return new D3D12PresentationContext(
                    arena, hwnd, devicePtr, queuePtr, swapchainPtr, allocatorPtr, listPtr, fencePtr,
                    captureTexture, allocationSize, captureGlTexture, semaphore, width, height);
        } catch (Throwable throwable) {
            arena.close();
            throw throwable;
        }
    }

    private static void diagnoseSwapchainHook(MemorySegment swapchain) {
        try {
            // IDXGISwapChain vtable: slot 8 = Present, slot 9 = GetBuffer. If RTSS/Afterburner
            // wrapped the swap chain it replaces the Present entry, so its address would fall
            // outside the same module as GetBuffer (or its entry bytes would be a JMP detour).
            MemorySegment vtable = swapchain.reinterpret(8).get(ADDRESS, 0).reinterpret(8L * 12);
            MemorySegment presentFunc = vtable.get(ADDRESS, 8L * 8);
            MemorySegment getBufferFunc = vtable.get(ADDRESS, 8L * 9);
            MemorySegment entry = presentFunc.reinterpret(8);
            StringBuilder bytes = new StringBuilder();
            for (int i = 0; i < 8; i++) {
                bytes.append(String.format("%02x ", entry.get(JAVA_BYTE, i)));
            }
            io.homo.superresolution.common.SuperResolution.LOGGER.info(
                    "[D3D12] swapchain vtable present={} getBuffer={} sameModule={} presentEntry={}",
                    Long.toHexString(presentFunc.address()),
                    Long.toHexString(getBufferFunc.address()),
                    (presentFunc.address() >>> 32) == (getBufferFunc.address() >>> 32),
                    bytes);
        } catch (Throwable ignored) {
            // Diagnostic only; never fail presentation setup over it.
        }
    }

    private static void diagnoseNativeEntryHooks() {
        try (Arena diagArena = Arena.ofConfined()) {
            SymbolLookup dxgi = SymbolLookup.libraryLookup("dxgi.dll", diagArena);
            SymbolLookup d3d12 = SymbolLookup.libraryLookup("d3d12.dll", diagArena);
            checkNativeEntry(dxgi, "CreateDXGIFactory2");
            checkNativeEntry(d3d12, "D3D12CreateDevice");
        } catch (Throwable ignored) {
            // Diagnostic only.
        }
    }

    private static void checkNativeEntry(SymbolLookup library, String name) {
        library.find(name).ifPresent(addr -> {
            MemorySegment entry = MemorySegment.ofAddress(addr.address()).reinterpret(8);
            StringBuilder bytes = new StringBuilder();
            for (int i = 0; i < 8; i++) {
                bytes.append(String.format("%02x ", entry.get(JAVA_BYTE, i)));
            }
            io.homo.superresolution.common.SuperResolution.LOGGER.info(
                    "[D3D12] hook {} addr={} entry={}", name,
                    Long.toHexString(addr.address()), bytes);
        });
    }

    private static MemorySegment findAdapter(
            windows.win32.graphics.dxgi.IDXGIFactory6 factory,
            Arena arena,
            long adapterLuid) {
        for (int i = 0; i < 16; i++) {
            MemorySegment ppAdapter = arena.allocate(ADDRESS);
            int hr = factory.EnumAdapters1(i, ppAdapter);
            if (hr == 0x887A0027 /* DXGI_ERROR_NOT_FOUND */) {
                break;
            }
            if (hr < 0) {
                continue;
            }
            MemorySegment adapter = ppAdapter.get(ADDRESS, 0);
            if (adapter.address() == 0) {
                continue;
            }
            MemorySegment desc = arena.allocate(
                    windows.win32.graphics.dxgi.DXGI_ADAPTER_DESC1.layout());
            windows.win32.graphics.dxgi.IDXGIAdapter1.wrap(adapter).GetDesc1(desc);
            MemorySegment luid = windows.win32.graphics.dxgi.DXGI_ADAPTER_DESC1.AdapterLuid(desc);
            long low = Integer.toUnsignedLong(
                    windows.win32.foundation.LUID.LowPart(luid));
            long high = Integer.toUnsignedLong(
                    windows.win32.foundation.LUID.HighPart(luid));
            if ((low | (high << 32)) == adapterLuid) {
                io.homo.superresolution.common.SuperResolution.LOGGER.info(
                        "[D3D12] matched adapter LUID={} name='{}'",
                        adapterLuid,
                        windows.win32.graphics.dxgi.DXGI_ADAPTER_DESC1.Description(desc)
                                .getString(0, java.nio.charset.StandardCharsets.UTF_16LE));
                return adapter;
            }
        }
        return MemorySegment.NULL;
    }

    private static MemorySegment createCaptureTexture(
            Arena arena,
            windows.win32.graphics.direct3d12.ID3D12Device device,
            MemorySegment resDesc) {
        MemorySegment heapProps = arena.allocate(
                windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.layout());
        windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.Type(
                heapProps, windows.win32.graphics.direct3d12.D3D12_HEAP_TYPE.DEFAULT);
        windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.CPUPageProperty(heapProps, 0);
        windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.MemoryPoolPreference(heapProps, 0);
        windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.CreationNodeMask(heapProps, 1);
        windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.VisibleNodeMask(heapProps, 1);

        MemorySegment ppResource = arena.allocate(ADDRESS);
        checkHr(device.CreateCommittedResource(
                heapProps, windows.win32.graphics.direct3d12.D3D12_HEAP_FLAGS.D3D12_HEAP_FLAG_SHARED,
                resDesc, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COMMON,
                MemorySegment.NULL, windows.win32.graphics.direct3d12.ID3D12Resource.iid(),
                ppResource));
        return ppResource.get(ADDRESS, 0);
    }

    private static MemorySegment fillResourceDesc(Arena arena, int width, int height) {
        MemorySegment resDesc = arena.allocate(
                windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.layout());
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Dimension(
                resDesc, windows.win32.graphics.direct3d12.D3D12_RESOURCE_DIMENSION.TEXTURE2D);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Alignment(resDesc, 0);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Width(resDesc, width);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Height(resDesc, height);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.DepthOrArraySize(resDesc, (short) 1);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.MipLevels(resDesc, (short) 1);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Format(
                resDesc, windows.win32.graphics.dxgi.common.DXGI_FORMAT.R8G8B8A8_UNORM);
        MemorySegment sampleDesc = arena.allocate(
                windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.layout());
        windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.Count(sampleDesc, 1);
        windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.Quality(sampleDesc, 0);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.SampleDesc(resDesc, sampleDesc);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Layout(
                resDesc, windows.win32.graphics.direct3d12.D3D12_TEXTURE_LAYOUT.UNKNOWN);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Flags(
                resDesc, windows.win32.graphics.direct3d12.D3D12_RESOURCE_FLAGS.D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);
        return resDesc;
    }

    private static long queryAllocationSize(
            Arena arena,
            windows.win32.graphics.direct3d12.ID3D12Device device,
            MemorySegment resDesc) {
        // The GL import size must cover the real committed allocation. GetResourceAllocationInfo
        // cannot be called through FFM (struct-by-value ABI crashes the JVM) and the copyable
        // footprint can be smaller than the allocation (verified: 1920x991 copyable=7610880 is
        // rejected, tile-rounded 7864320 is accepted). For an R8G8B8A8 standard-swizzle texture
        // the allocation is 64KB tiles of 128x128 texels, so round the texel count up to tiles.
        long width = windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Width(resDesc);
        long height = windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Height(resDesc);
        long tilesX = (width + 127) / 128;
        long tilesY = (height + 127) / 128;
        return tilesX * tilesY * 65536L;
    }

    private static long createSharedHandle(
            Arena arena,
            windows.win32.graphics.direct3d12.ID3D12Device device,
            MemorySegment object) {
        MemorySegment ppHandle = arena.allocate(ADDRESS);
        checkHr(device.CreateSharedHandle(
                object, MemorySegment.NULL, 0x10000000 /* GENERIC_ALL */, MemorySegment.NULL, ppHandle));
        return ppHandle.get(JAVA_LONG, 0);
    }

    private static void checkHr(int hr) {
        if (hr < 0) {
            throw new IllegalStateException(
                    "D3D12/DXGI call failed with HRESULT 0x" + Integer.toHexString(hr));
        }
    }

    private static long queryOpenGlAdapterLuid() {
        try (MemoryStack stack = MemoryStack.stackPush()) {
            ByteBuffer luid = stack.calloc(EXTMemoryObjectWin32.GL_LUID_SIZE_EXT)
                    .order(ByteOrder.nativeOrder());
            EXTMemoryObject.glGetUnsignedBytevEXT(
                    EXTMemoryObjectWin32.GL_DEVICE_LUID_EXT, luid);
            long lowPart = Integer.toUnsignedLong(luid.getInt(0));
            long highPart = Integer.toUnsignedLong(luid.getInt(4));
            return lowPart | (highPart << 32);
        }
    }

    private static TextureDescription textureDescription(int width, int height) {
        return TextureDescription.create()
                .type(TextureType.Texture2D)
                .width(width)
                .height(height)
                .format(TextureFormat.RGBA8)
                .usages(TextureUsages.create().sampler().storage())
                .label("D3D12PresentationCapture")
                .build();
    }

    public void present(ITexture finalColor) {
        long captureValue = nextGlFence;
        // The GL work below (semaphore layout barriers + flipY compute) must not leak
        // GL state into the next frame: the Vulkan path wraps it in a GlState, and without
        // that the leaked texture-unit/program state makes font rendering sample the wrong
        // atlas (purple/black missing-texture stripes).
        try (io.homo.superresolution.core.graphics.opengl.GlState ignored =
                     new io.homo.superresolution.core.graphics.opengl.GlState()) {
            if (lastD3d12Signal > 0) {
                semaphore.waitFor(
                        lastD3d12Signal,
                        new int[]{Math.toIntExact(captureGlTexture.handle())},
                        new int[]{GL_LAYOUT_GENERAL_EXT});
            }
            InteropResourcesConverter.flipY(finalColor, captureGlTexture);
            semaphore.signal(
                    captureValue,
                    new int[]{Math.toIntExact(captureGlTexture.handle())},
                    new int[]{GL_LAYOUT_GENERAL_EXT});
        }

        windows.win32.graphics.direct3d12.ID3D12CommandQueue queueIface =
                windows.win32.graphics.direct3d12.ID3D12CommandQueue.wrap(queue);
        windows.win32.graphics.direct3d12.ID3D12Fence fenceIface =
                windows.win32.graphics.direct3d12.ID3D12Fence.wrap(fence);
        windows.win32.graphics.dxgi.IDXGISwapChain3 swapchainIface =
                windows.win32.graphics.dxgi.IDXGISwapChain3.wrap(swapchain);
        windows.win32.graphics.direct3d12.ID3D12CommandAllocator allocatorIface =
                windows.win32.graphics.direct3d12.ID3D12CommandAllocator.wrap(commandAllocator);
        windows.win32.graphics.direct3d12.ID3D12GraphicsCommandList listIface =
                windows.win32.graphics.direct3d12.ID3D12GraphicsCommandList.wrap(commandList);

        queueIface.Wait(fence, captureValue);

        checkHr(allocatorIface.Reset());
        checkHr(listIface.Reset(commandAllocator, MemorySegment.NULL));

        int imageIndex = swapchainIface.GetCurrentBackBufferIndex();
        MemorySegment ppBackBuffer = arena.allocate(ADDRESS);
        checkHr(swapchainIface.GetBuffer(
                imageIndex, windows.win32.graphics.direct3d12.ID3D12Resource.iid(), ppBackBuffer));
        MemorySegment backBuffer = ppBackBuffer.get(ADDRESS, 0);

        MemorySegment barriers = arena.allocate(
                windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.layout(), 2);
        MemorySegment b0 = barriers;
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.Type(
                b0, windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER_TYPE.TRANSITION);
        MemorySegment t0 = windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.Transition(b0);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.pResource(t0, captureTexture);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateBefore(
                t0, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COMMON);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateAfter(
                t0, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COPY_SOURCE);
        MemorySegment b1 = barriers.asSlice(
                windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.layout().byteSize());
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.Type(
                b1, windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER_TYPE.TRANSITION);
        MemorySegment t1 = windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.Transition(b1);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.pResource(t1, backBuffer);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateBefore(
                t1, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COMMON);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateAfter(
                t1, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COPY_DEST);
        listIface.ResourceBarrier(2, barriers);

        MemorySegment dst = arena.allocate(
                windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.layout());
        windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.pResource(dst, backBuffer);
        windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.Type(
                dst, windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_TYPE.SUBRESOURCE_INDEX);
        windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.SubresourceIndex(dst, 0);
        MemorySegment src = arena.allocate(
                windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.layout());
        windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.pResource(src, captureTexture);
        windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.Type(
                src, windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_TYPE.SUBRESOURCE_INDEX);
        windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.SubresourceIndex(src, 0);
        MemorySegment srcBox = arena.allocate(windows.win32.graphics.direct3d12.D3D12_BOX.layout());
        windows.win32.graphics.direct3d12.D3D12_BOX.left(srcBox, 0);
        windows.win32.graphics.direct3d12.D3D12_BOX.top(srcBox, 0);
        windows.win32.graphics.direct3d12.D3D12_BOX.front(srcBox, 0);
        windows.win32.graphics.direct3d12.D3D12_BOX.right(srcBox, width);
        windows.win32.graphics.direct3d12.D3D12_BOX.bottom(srcBox, height);
        windows.win32.graphics.direct3d12.D3D12_BOX.back(srcBox, 1);
        listIface.CopyTextureRegion(dst, 0, 0, 0, src, srcBox);

        windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateBefore(
                t1, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COPY_DEST);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateAfter(
                t1, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COMMON);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateBefore(
                t0, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COPY_SOURCE);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateAfter(
                t0, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COMMON);
        listIface.ResourceBarrier(2, barriers);

        checkHr(listIface.Close());
        queueIface.ExecuteCommandLists(1, arena.allocateFrom(ADDRESS, commandList));

        // Wait until the GL flipY has actually completed on the GPU (fence >= captureValue)
        // before presenting. Without this the D3D12 copy can race ahead of flipY and the
        // presented back buffer shows an earlier frame ("rolling back to a previous frame").
        for (int i = 0; i < 2000; i++) {
            if (fenceIface.GetCompletedValue() >= captureValue) {
                break;
            }
            try {
                Thread.sleep(1);
            } catch (InterruptedException interrupted) {
                Thread.currentThread().interrupt();
                break;
            }
        }
        if (fenceIface.GetCompletedValue() < captureValue) {
            io.homo.superresolution.common.SuperResolution.LOGGER.warn(
                    "[D3D12] timed out waiting for flipY fence {} (completed {})",
                    captureValue, fenceIface.GetCompletedValue());
        }

        swapchainIface.Present(vsync ? 1 : 0, 0);

        long signalValue = nextGlFence + 1;
        queueIface.Signal(fence, signalValue);
        lastD3d12Signal = signalValue;
        nextGlFence += 2;
    }

    private static MemorySegment buildSwapchainDesc(Arena arena, int width, int height) {
        MemorySegment scDesc = arena.allocate(
                windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.layout());
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.Width(scDesc, width);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.Height(scDesc, height);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.Format(
                scDesc, windows.win32.graphics.dxgi.common.DXGI_FORMAT.R8G8B8A8_UNORM);
        MemorySegment sampleDesc = arena.allocate(
                windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.layout());
        windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.Count(sampleDesc, 1);
        windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.Quality(sampleDesc, 0);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.SampleDesc(scDesc, sampleDesc);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.BufferUsage(scDesc, 0x20);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.BufferCount(scDesc, 3);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.SwapEffect(
                scDesc, windows.win32.graphics.dxgi.DXGI_SWAP_EFFECT.FLIP_SEQUENTIAL);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.Flags(scDesc, 0);
        return scDesc;
    }

    public void resize(int newWidth, int newHeight) {
        if (newWidth == width && newHeight == height) {
            return;
        }
        // FLIP model: ResizeBuffers returns DXGI_ERROR_NOT_CURRENTLY_AVAILABLE while the
        // previous frame's back buffer is still referenced by in-flight GPU work, and the
        // DWM compositor may hold it a while longer after the GPU is idle. Wait and retry
        // over a longer window, then fall back to recreating the swap chain like the
        // reference Vulkan surface does.
        waitForGpu();
        windows.win32.graphics.dxgi.IDXGISwapChain3 swapchainIface =
                windows.win32.graphics.dxgi.IDXGISwapChain3.wrap(swapchain);
        int lastHr = 0;
        for (int retry = 0; retry < 8; retry++) {
            if (retry > 0) {
                try {
                    Thread.sleep(32L * retry);
                } catch (InterruptedException interrupted) {
                    Thread.currentThread().interrupt();
                    break;
                }
                waitForGpu();
            }
            lastHr = swapchainIface.ResizeBuffers1(3, newWidth, newHeight,
                    windows.win32.graphics.dxgi.common.DXGI_FORMAT.R8G8B8A8_UNORM, 0,
                    MemorySegment.NULL, MemorySegment.NULL);
            if (lastHr >= 0) {
                break;
            }
        }
        if (lastHr < 0) {
            try {
                recreateSwapchain(newWidth, newHeight);
            } catch (Throwable throwable) {
                io.homo.superresolution.common.SuperResolution.LOGGER.warn(
                        "[D3D12] ResizeBuffers to {}x{} failed 0x{} and recreate failed; "
                                + "keeping {}x{}",
                        newWidth, newHeight, Integer.toHexString(lastHr), width, height,
                        throwable);
                return;
            }
        }
        // The back buffer changed size, so the capture texture must be rebuilt to match;
        // otherwise present copies a stale-sized source into the new back buffer.
        recreateCaptureResources(newWidth, newHeight);
        width = newWidth;
        height = newHeight;
    }

    private void recreateSwapchain(int newWidth, int newHeight) {
        // A window may only own one flip-model swap chain, so release the old one
        // before creating a replacement (otherwise CreateSwapChainForHwnd fails).
        if (swapchain.address() != 0) {
            windows.win32.graphics.dxgi.IDXGISwapChain3.wrap(swapchain).Release();
        }
        MemorySegment ppFactory = arena.allocate(ADDRESS);
        checkHr(windows.win32.graphics.dxgi.Apis.CreateDXGIFactory2(
                0, windows.win32.graphics.dxgi.IDXGIFactory6.iid(), ppFactory));
        windows.win32.graphics.dxgi.IDXGIFactory6 factory =
                windows.win32.graphics.dxgi.IDXGIFactory6.wrap(ppFactory.get(ADDRESS, 0));
        MemorySegment scDesc = buildSwapchainDesc(arena, newWidth, newHeight);
        MemorySegment ppNew = arena.allocate(ADDRESS);
        checkHr(factory.CreateSwapChainForHwnd(
                queue, MemorySegment.ofAddress(hwnd), scDesc, MemorySegment.NULL,
                MemorySegment.NULL, ppNew));
        this.swapchain = ppNew.get(ADDRESS, 0);
        io.homo.superresolution.common.SuperResolution.LOGGER.info(
                "[D3D12] swapchain recreated to {}x{}", newWidth, newHeight);
    }

    private void recreateCaptureResources(int newWidth, int newHeight) {
        // Build the new capture texture fully before touching the old one, so a failure
        // here leaves the previous capture intact instead of leaving captureGlTexture null
        // (which would NPE in present() and crash the game).
        windows.win32.graphics.direct3d12.ID3D12Device deviceIface =
                windows.win32.graphics.direct3d12.ID3D12Device.wrap(device);
        MemorySegment captureDesc = fillResourceDesc(arena, newWidth, newHeight);
        MemorySegment newCaptureTexture = createCaptureTexture(arena, deviceIface, captureDesc);
        long captureHandle = createSharedHandle(arena, deviceIface, newCaptureTexture);
        long newSize = queryAllocationSize(arena, deviceIface, captureDesc);
        D3D12InteropContext.Resource glResource = new D3D12InteropContext.Resource(
                0, 0, captureHandle, newSize,
                textureDescription(newWidth, newHeight), SRSurfaceFormat.R8G8B8A8_UNORM);
        GlD3D12ImportableTexture2D newCaptureGlTexture = new GlD3D12ImportableTexture2D(glResource);
        if (captureGlTexture != null) {
            captureGlTexture.destroy();
        }
        this.captureTexture = newCaptureTexture;
        this.captureAllocationSize = newSize;
        this.captureGlTexture = newCaptureGlTexture;
    }

    private void waitForGpu() {
        if (lastD3d12Signal <= 0) {
            return;
        }
        windows.win32.graphics.direct3d12.ID3D12Fence fenceIface =
                windows.win32.graphics.direct3d12.ID3D12Fence.wrap(fence);
        for (int i = 0; i < 2000; i++) {
            if (fenceIface.GetCompletedValue() >= lastD3d12Signal) {
                return;
            }
            try {
                Thread.sleep(1);
            } catch (InterruptedException interrupted) {
                Thread.currentThread().interrupt();
                return;
            }
        }
        io.homo.superresolution.common.SuperResolution.LOGGER.warn(
                "[D3D12] timed out waiting for GPU idle before resize");
    }

    public int width() {
        return width;
    }

    public int height() {
        return height;
    }

    /** Matches the OpenGL vsync setting: flip-model Present uses syncInterval 1 (wait for
     * vsync) when vsync is on, 0 (immediate) otherwise. */
    public void setVsync(boolean enabled) {
        this.vsync = enabled;
    }

    @Override
    public void close() {
        arena.close();
    }

    public static boolean isNativeAvailable() {
        // The FFM bindings are compiled in; D3D12 presentation only works on Windows.
        return io.homo.superresolution.api.platform.Platform.currentPlatform.getOS().type
                == io.homo.superresolution.api.platform.OperatingSystemType.WINDOWS;
    }
}
#else
public final class D3D12PresentationContext {
}
#endif
