/*
 * Super Resolution
 * Copyright (c) 2026. 187J3X1-114514
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

package io.homo.superresolution.core.graphics.d3d12;

#if MC_VER >= MC_1_20_1 && MC_VER < MC_26_2
import io.homo.superresolution.common.framegeneration.D3D12FrameGeneration;
import io.homo.superresolution.common.lowlatency.LowLatency;
import io.homo.superresolution.common.upscale.InteropResourcesConverter;
import io.homo.superresolution.core.NativeLibManager;
import io.homo.superresolution.core.graphics.impl.texture.ITexture;
import io.homo.superresolution.core.graphics.impl.texture.TextureDescription;
import io.homo.superresolution.core.graphics.impl.texture.TextureFormat;
import io.homo.superresolution.core.graphics.impl.texture.TextureType;
import io.homo.superresolution.core.graphics.impl.texture.TextureUsages;
import io.homo.superresolution.core.graphics.opengl.GlState;
import io.homo.superresolution.srapi.SRSurfaceFormat;
import org.lwjgl.opengl.EXTMemoryObject;
import org.lwjgl.opengl.EXTMemoryObjectWin32;
import org.lwjgl.opengl.GL;
import org.lwjgl.system.MemoryStack;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.invoke.MethodHandle;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_BYTE;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
import static org.lwjgl.opengl.EXTSemaphore.GL_LAYOUT_GENERAL_EXT;

/**
 * D3D12 presentation via the Java FFM (Foreign Function & Memory API) bindings
 * generated by WindowsApiGenerator. Owns a DXGI flip-model swap chain on the
 * Minecraft window (created GLFW_NO_API, so it carries no OpenGL pixel format),
 * a shared capture texture and a shared timeline fence. The OpenGL side flips
 * the final frame into the capture texture; this context blits it into the swap
 * chain back buffer and presents.
 */
public final class D3D12PresentationContext implements AutoCloseable {
    /**
     * Cached Present vtable slot (slot 8) of the current swap chain. XeSS-FG's proxy
     * nulls its Present slot after the first Present, so once captured we keep calling
     * this function pointer directly (OptiScaler does the same by detouring o_FGSCPresent
     * once instead of re-reading the vtable each present).
     */
    private static final Linker NATIVE_LINKER = Linker.nativeLinker();
    // downcallHandle prepends the symbol (function pointer) argument, so the descriptor
    // only lists (this, syncInterval, flags).
    private static final FunctionDescriptor PRESENT_DESC =
            FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT);
    private static final MethodHandle PRESENT_DOWN = NATIVE_LINKER.downcallHandle(PRESENT_DESC);
    private static volatile long cachedXefgPresentFn;
    /** kernel32 event waits used for the flipY fence instead of 1ms polling. */
    private static final MethodHandle CREATE_EVENT = NATIVE_LINKER.defaultLookup()
            .find("CreateEventW").map(sym -> NATIVE_LINKER.downcallHandle(
                    sym, FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS)))
            .orElse(null);
    private static final MethodHandle WAIT_SINGLE_OBJECT = NATIVE_LINKER.defaultLookup()
            .find("WaitForSingleObject").map(sym -> NATIVE_LINKER.downcallHandle(
                    sym, FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT)))
            .orElse(null);
    private static final MethodHandle CLOSE_HANDLE = NATIVE_LINKER.defaultLookup()
            .find("CloseHandle").map(sym -> NATIVE_LINKER.downcallHandle(
                    sym, FunctionDescriptor.of(JAVA_INT, ADDRESS)))
            .orElse(null);

    private final Arena arena;
    private final long hwnd;
    private final MemorySegment device;
    private final MemorySegment queue;
    private MemorySegment swapchain;
    private MemorySegment factory;
    /** Ring depth for command allocators: only submits older than this are waited on, so the
     * render thread never blocks on the current frame's GPU work (mirrors the Vulkan
     * presentation's {@code MAX_IN_FLIGHT_FRAMES} ring that waits N-1 frames back). */
    private static final int COMMAND_RING_DEPTH = 3;
    private final MemorySegment[] commandAllocators;
    private final long[] commandRingFences = new long[COMMAND_RING_DEPTH];
    private int commandRingSlot;
    private final MemorySegment commandList;
    private final MemorySegment fence;
    private MemorySegment captureTexture;
    private long captureAllocationSize;

    private GlD3D12ImportableTexture2D captureGlTexture;
    /** R32_FLOAT depth and R16G16_FLOAT motion-vector textures for XeSS-FG, written from GL. */
    private MemorySegment depthTexture;
    private long depthAllocationSize;
    private GlD3D12ImportableTexture2D depthGlTexture;
    private MemorySegment mvTexture;
    private long mvAllocationSize;
    private GlD3D12ImportableTexture2D mvGlTexture;
    /**
     * Size of the shared depth/motion-vector textures. These follow the frame inputs'
     * native dispatch resolution (low-res MV path), not the presentation extent; the
     * tagged resourceSize tells XeSS-FG to upsample/dilate them internally.
     */
    private int frameInputWidth;
    private int frameInputHeight;
    /** R8G8B8A8 HUD-less color for XeSS-FG UI composition, written from GL. */
    private MemorySegment hudlessTexture;
    private long hudlessAllocationSize;
    private GlD3D12ImportableTexture2D hudlessGlTexture;
    private final D3D12InteropSemaphore semaphore;
    /** Back buffers cached per swap-chain index (one COM reference each), avoiding a GetBuffer/Release pair every present. */
    private final MemorySegment[] backBuffers = new MemorySegment[8];
    /** Auto-reset kernel event for the flipY fence wait; created lazily. */
    private MemorySegment fenceEvent = MemorySegment.NULL;
    private int width;
    private int height;
    private long nextGlFence = 1;
    private long lastD3d12Signal;
    private volatile boolean vsync = true;
    /**
     * Whether the DXGI factory supports DXGI_FEATURE_PRESENT_ALLOW_TEARING (Windows 10
     * 1703+). A windowed flip-model Present with SyncInterval 0 is still throttled to the
     * monitor refresh rate by DWM unless the swap chain was created with
     * DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING and Present passes DXGI_PRESENT_ALLOW_TEARING —
     * without it "vsync off" locks the game to the refresh rate, while the Vulkan
     * presentation runs uncapped (VK_PRESENT_MODE_IMMEDIATE_KHR). The XeSS-FG developer
     * guide prescribes the same: Present(0, DXGI_PRESENT_ALLOW_TEARING).
     */
    private static volatile boolean allowTearingSupported;

    private D3D12PresentationContext(
            Arena arena, long hwnd, MemorySegment device, MemorySegment queue, MemorySegment swapchain,
            MemorySegment factory, MemorySegment[] commandAllocators, MemorySegment commandList,
            MemorySegment fence, MemorySegment captureTexture, long captureAllocationSize,
            GlD3D12ImportableTexture2D captureGlTexture,
            MemorySegment depthTexture, long depthAllocationSize, GlD3D12ImportableTexture2D depthGlTexture,
            MemorySegment mvTexture, long mvAllocationSize, GlD3D12ImportableTexture2D mvGlTexture,
            MemorySegment hudlessTexture, long hudlessAllocationSize, GlD3D12ImportableTexture2D hudlessGlTexture,
            D3D12InteropSemaphore semaphore, int width, int height) {
        this.arena = arena;
        this.hwnd = hwnd;
        this.device = device;
        this.queue = queue;
        this.swapchain = swapchain;
        this.factory = factory;
        this.commandAllocators = commandAllocators;
        this.commandList = commandList;
        this.fence = fence;
        this.captureTexture = captureTexture;
        this.captureAllocationSize = captureAllocationSize;
        this.captureGlTexture = captureGlTexture;
        this.depthTexture = depthTexture;
        this.depthAllocationSize = depthAllocationSize;
        this.depthGlTexture = depthGlTexture;
        this.mvTexture = mvTexture;
        this.mvAllocationSize = mvAllocationSize;
        this.mvGlTexture = mvGlTexture;
        this.hudlessTexture = hudlessTexture;
        this.hudlessAllocationSize = hudlessAllocationSize;
        this.hudlessGlTexture = hudlessGlTexture;
        this.semaphore = semaphore;
        this.width = width;
        this.height = height;
    }

    public static D3D12PresentationContext create(long hwnd, int width, int height) {
        // The hidden GL helper window's capabilities may not carry the memory-object
        // extensions if they were captured on a different context; refresh them now
        // (the render thread current context is the hidden GL window).
        GL.createCapabilities();
        io.homo.superresolution.common.SuperResolution.LOGGER.info(
                "[D3D12] create: current={} renderHandle={} gl={} renderer='{}' ext_mem={} ext_mem_win32={} ext_sem_win32={}",
                org.lwjgl.glfw.GLFW.glfwGetCurrentContext(),
                io.homo.superresolution.common.presentation.window.PresentationWindowState.renderHandle(),
                org.lwjgl.opengl.GL11.glGetString(org.lwjgl.opengl.GL11.GL_VERSION),
                org.lwjgl.opengl.GL11.glGetString(org.lwjgl.opengl.GL11.GL_RENDERER),
                GL.getCapabilities().GL_EXT_memory_object,
                GL.getCapabilities().GL_EXT_memory_object_win32,
                GL.getCapabilities().GL_EXT_semaphore_win32);
        if (!GL.getCapabilities().GL_EXT_memory_object_win32 ||
                !GL.getCapabilities().GL_EXT_semaphore_win32) {
            throw new UnsupportedOperationException(
                    "D3D12 presentation requires GL_EXT_memory_object_win32 and GL_EXT_semaphore_win32.");
        }
        Arena arena = Arena.ofShared();
        try {
            long adapterLuid = queryOpenGlAdapterLuid();

            MemorySegment ppFactory = arena.allocate(ADDRESS);
            checkHr(windows.win32.graphics.dxgi.Apis.CreateDXGIFactory2(
                    0, windows.win32.graphics.dxgi.IDXGIFactory6.iid(), ppFactory));
            windows.win32.graphics.dxgi.IDXGIFactory6 factory =
                    windows.win32.graphics.dxgi.IDXGIFactory6.wrap(ppFactory.get(ADDRESS, 0));
            allowTearingSupported = queryAllowTearing(factory);

            MemorySegment adapter = findAdapter(factory, arena, adapterLuid);
            if (adapter.address() == 0) {
                throw new IllegalStateException("No D3D12 adapter matches the OpenGL device LUID.");
            }

            MemorySegment ppDevice = arena.allocate(ADDRESS);
            checkHr(windows.win32.graphics.direct3d12.Apis.D3D12CreateDevice(
                    adapter, windows.win32.graphics.direct3d.D3D_FEATURE_LEVEL._12_0,
                    windows.win32.graphics.direct3d12.ID3D12Device.iid(), ppDevice));
            windows.win32.graphics.direct3d12.ID3D12Device device =
                    windows.win32.graphics.direct3d12.ID3D12Device.wrap(ppDevice.get(ADDRESS, 0));
            MemorySegment devicePtr = ppDevice.get(ADDRESS, 0);

            MemorySegment queueDesc = arena.allocate(
                    windows.win32.graphics.direct3d12.D3D12_COMMAND_QUEUE_DESC.layout());
            windows.win32.graphics.direct3d12.D3D12_COMMAND_QUEUE_DESC.Type(
                    queueDesc, windows.win32.graphics.direct3d12.D3D12_COMMAND_LIST_TYPE.DIRECT);
            windows.win32.graphics.direct3d12.D3D12_COMMAND_QUEUE_DESC.Priority(queueDesc, 0);
            windows.win32.graphics.direct3d12.D3D12_COMMAND_QUEUE_DESC.Flags(queueDesc, 0);
            windows.win32.graphics.direct3d12.D3D12_COMMAND_QUEUE_DESC.NodeMask(queueDesc, 0);
            MemorySegment ppQueue = arena.allocate(ADDRESS);
            checkHr(device.CreateCommandQueue(
                    queueDesc, windows.win32.graphics.direct3d12.ID3D12CommandQueue.iid(), ppQueue));
            MemorySegment queuePtr = ppQueue.get(ADDRESS, 0);

            MemorySegment scDesc = buildSwapchainDesc(arena, width, height);
            MemorySegment ppSwapchain = arena.allocate(ADDRESS);
            checkHr(factory.CreateSwapChainForHwnd(
                    queuePtr, MemorySegment.ofAddress(hwnd), scDesc, MemorySegment.NULL,
                    MemorySegment.NULL, ppSwapchain));
            MemorySegment swapchainPtr = ppSwapchain.get(ADDRESS, 0);
            diagnoseSwapchainHook(swapchainPtr);
            diagnoseNativeEntryHooks();

            MemorySegment[] allocators = new MemorySegment[COMMAND_RING_DEPTH];
            for (int i = 0; i < COMMAND_RING_DEPTH; i++) {
                MemorySegment ppAllocator = arena.allocate(ADDRESS);
                checkHr(device.CreateCommandAllocator(
                        windows.win32.graphics.direct3d12.D3D12_COMMAND_LIST_TYPE.DIRECT,
                        windows.win32.graphics.direct3d12.ID3D12CommandAllocator.iid(), ppAllocator));
                allocators[i] = ppAllocator.get(ADDRESS, 0);
            }
            MemorySegment ppList = arena.allocate(ADDRESS);
            checkHr(device.CreateCommandList(
                    0, windows.win32.graphics.direct3d12.D3D12_COMMAND_LIST_TYPE.DIRECT,
                    allocators[0], MemorySegment.NULL,
                    windows.win32.graphics.direct3d12.ID3D12GraphicsCommandList.iid(), ppList));
            MemorySegment listPtr = ppList.get(ADDRESS, 0);
            checkHr(windows.win32.graphics.direct3d12.ID3D12GraphicsCommandList.wrap(listPtr)
                    .Close());

            MemorySegment ppFence = arena.allocate(ADDRESS);
            checkHr(device.CreateFence(
                    0, windows.win32.graphics.direct3d12.D3D12_FENCE_FLAGS.D3D12_FENCE_FLAG_SHARED,
                    windows.win32.graphics.direct3d12.ID3D12Fence.iid(), ppFence));
            MemorySegment fencePtr = ppFence.get(ADDRESS, 0);
            long fenceHandle = createSharedHandle(arena, device, fencePtr);

            MemorySegment captureDesc = fillResourceDesc(
                    arena, width, height, windows.win32.graphics.dxgi.common.DXGI_FORMAT.R8G8B8A8_UNORM);
            MemorySegment captureTexture = createCaptureTexture(arena, device, captureDesc);
            long captureHandle = createSharedHandle(arena, device, captureTexture);
            long allocationSize = queryAllocationSize(arena, device, captureDesc);

            D3D12InteropSemaphore semaphore = new D3D12InteropSemaphore(fenceHandle);
            D3D12InteropContext.Resource glResource = new D3D12InteropContext.Resource(
                    0, 0, captureHandle, allocationSize,
                    textureDescription(width, height, TextureFormat.RGBA8, "D3D12PresentationCapture"),
                    SRSurfaceFormat.R8G8B8A8_UNORM);
            GlD3D12ImportableTexture2D captureGlTexture =
                    new GlD3D12ImportableTexture2D(glResource);

            // R32_FLOAT depth for XeSS-FG, written from GL each frame.
            MemorySegment depthDesc = fillResourceDesc(
                    arena, width, height, windows.win32.graphics.dxgi.common.DXGI_FORMAT.R32_FLOAT);
            MemorySegment depthTexture = createCaptureTexture(arena, device, depthDesc);
            long depthHandle = createSharedHandle(arena, device, depthTexture);
            long depthSize = queryAllocationSize(arena, device, depthDesc);
            GlD3D12ImportableTexture2D depthGlTexture = new GlD3D12ImportableTexture2D(
                    new D3D12InteropContext.Resource(0, 0, depthHandle, depthSize,
                            textureDescription(width, height, TextureFormat.R32F, "D3D12PresentationDepth"),
                            SRSurfaceFormat.R32_FLOAT));

            // R16G16_FLOAT motion vectors for XeSS-FG, written from GL each frame.
            MemorySegment mvDesc = fillResourceDesc(
                    arena, width, height, windows.win32.graphics.dxgi.common.DXGI_FORMAT.R16G16_FLOAT);
            MemorySegment mvTexture = createCaptureTexture(arena, device, mvDesc);
            long mvHandle = createSharedHandle(arena, device, mvTexture);
            long mvSize = queryAllocationSize(arena, device, mvDesc);
            GlD3D12ImportableTexture2D mvGlTexture = new GlD3D12ImportableTexture2D(
                    new D3D12InteropContext.Resource(0, 0, mvHandle, mvSize,
                            textureDescription(width, height, TextureFormat.RG16F, "D3D12PresentationMotionVector"),
                            SRSurfaceFormat.R16G16_FLOAT));

            // R8G8B8A8 HUD-less color for XeSS-FG UI composition (BACKBUFFER_HUDLESS):
            // same format and color space as the back buffer per the SDK requirements,
            // written from the pre-UI shader-compat color each frame.
            MemorySegment hudlessDesc = fillResourceDesc(
                    arena, width, height, windows.win32.graphics.dxgi.common.DXGI_FORMAT.R8G8B8A8_UNORM);
            MemorySegment hudlessTexture = createCaptureTexture(arena, device, hudlessDesc);
            long hudlessHandle = createSharedHandle(arena, device, hudlessTexture);
            long hudlessSize = queryAllocationSize(arena, device, hudlessDesc);
            GlD3D12ImportableTexture2D hudlessGlTexture = new GlD3D12ImportableTexture2D(
                    new D3D12InteropContext.Resource(0, 0, hudlessHandle, hudlessSize,
                            textureDescription(width, height, TextureFormat.RGBA8, "D3D12PresentationHudless"),
                            SRSurfaceFormat.R8G8B8A8_UNORM));

            D3D12PresentationContext presentationContext = new D3D12PresentationContext(
                    arena, hwnd, devicePtr, queuePtr, swapchainPtr, ppFactory.get(ADDRESS, 0),
                    allocators, listPtr, fencePtr,
                    captureTexture, allocationSize, captureGlTexture,
                    depthTexture, depthSize, depthGlTexture,
                    mvTexture, mvSize, mvGlTexture,
                    hudlessTexture, hudlessSize, hudlessGlTexture,
                    semaphore, width, height);
            // Placeholder size until the first dispatch decides the real frame-input
            // extent (ensureFrameInputResources rebuilds when it differs).
            presentationContext.frameInputWidth = width;
            presentationContext.frameInputHeight = height;
            return presentationContext;
        } catch (Throwable throwable) {
            arena.close();
            throw throwable;
        }
    }

    private static void diagnoseSwapchainHook(MemorySegment swapchain) {
        try {
            // IDXGISwapChain vtable: slot 8 = Present, slot 9 = GetBuffer. If RTSS/Afterburner
            // wrapped the swap chain it replaces the Present entry, so its address would fall
            // outside the same module as GetBuffer (or its entry bytes would be a JMP detour).
            MemorySegment vtable = swapchain.reinterpret(8).get(ADDRESS, 0).reinterpret(8L * 12);
            MemorySegment presentFunc = vtable.get(ADDRESS, 8L * 8);
            MemorySegment getBufferFunc = vtable.get(ADDRESS, 8L * 9);
            MemorySegment entry = presentFunc.reinterpret(8);
            StringBuilder bytes = new StringBuilder();
            for (int i = 0; i < 8; i++) {
                bytes.append(String.format("%02x ", entry.get(JAVA_BYTE, i)));
            }
            io.homo.superresolution.common.SuperResolution.LOGGER.info(
                    "[D3D12] swapchain vtable present={} getBuffer={} sameModule={} presentEntry={}",
                    Long.toHexString(presentFunc.address()),
                    Long.toHexString(getBufferFunc.address()),
                    (presentFunc.address() >>> 32) == (getBufferFunc.address() >>> 32),
                    bytes);
        } catch (Throwable ignored) {
            // Diagnostic only; never fail presentation setup over it.
        }
    }

    private static void diagnoseNativeEntryHooks() {
        try (Arena diagArena = Arena.ofConfined()) {
            SymbolLookup dxgi = SymbolLookup.libraryLookup("dxgi.dll", diagArena);
            SymbolLookup d3d12 = SymbolLookup.libraryLookup("d3d12.dll", diagArena);
            checkNativeEntry(dxgi, "CreateDXGIFactory2");
            checkNativeEntry(d3d12, "D3D12CreateDevice");
        } catch (Throwable ignored) {
            // Diagnostic only.
        }
    }

    private static void checkNativeEntry(SymbolLookup library, String name) {
        library.find(name).ifPresent(addr -> {
            MemorySegment entry = MemorySegment.ofAddress(addr.address()).reinterpret(8);
            StringBuilder bytes = new StringBuilder();
            for (int i = 0; i < 8; i++) {
                bytes.append(String.format("%02x ", entry.get(JAVA_BYTE, i)));
            }
            io.homo.superresolution.common.SuperResolution.LOGGER.info(
                    "[D3D12] hook {} addr={} entry={}", name,
                    Long.toHexString(addr.address()), bytes);
        });
    }

    private static MemorySegment findAdapter(
            windows.win32.graphics.dxgi.IDXGIFactory6 factory,
            Arena arena,
            long adapterLuid) {
        for (int i = 0; i < 16; i++) {
            MemorySegment ppAdapter = arena.allocate(ADDRESS);
            int hr = factory.EnumAdapters1(i, ppAdapter);
            if (hr == 0x887A0027 /* DXGI_ERROR_NOT_FOUND */) {
                break;
            }
            if (hr < 0) {
                continue;
            }
            MemorySegment adapter = ppAdapter.get(ADDRESS, 0);
            if (adapter.address() == 0) {
                continue;
            }
            MemorySegment desc = arena.allocate(
                    windows.win32.graphics.dxgi.DXGI_ADAPTER_DESC1.layout());
            windows.win32.graphics.dxgi.IDXGIAdapter1.wrap(adapter).GetDesc1(desc);
            MemorySegment luid = windows.win32.graphics.dxgi.DXGI_ADAPTER_DESC1.AdapterLuid(desc);
            long low = Integer.toUnsignedLong(
                    windows.win32.foundation.LUID.LowPart(luid));
            long high = Integer.toUnsignedLong(
                    windows.win32.foundation.LUID.HighPart(luid));
            if ((low | (high << 32)) == adapterLuid) {
                io.homo.superresolution.common.SuperResolution.LOGGER.info(
                        "[D3D12] matched adapter LUID={} name='{}'",
                        adapterLuid,
                        windows.win32.graphics.dxgi.DXGI_ADAPTER_DESC1.Description(desc)
                                .getString(0, java.nio.charset.StandardCharsets.UTF_16LE));
                return adapter;
            }
        }
        return MemorySegment.NULL;
    }

    private static MemorySegment createCaptureTexture(
            Arena arena,
            windows.win32.graphics.direct3d12.ID3D12Device device,
            MemorySegment resDesc) {
        MemorySegment heapProps = arena.allocate(
                windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.layout());
        windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.Type(
                heapProps, windows.win32.graphics.direct3d12.D3D12_HEAP_TYPE.DEFAULT);
        windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.CPUPageProperty(heapProps, 0);
        windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.MemoryPoolPreference(heapProps, 0);
        windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.CreationNodeMask(heapProps, 1);
        windows.win32.graphics.direct3d12.D3D12_HEAP_PROPERTIES.VisibleNodeMask(heapProps, 1);

        MemorySegment ppResource = arena.allocate(ADDRESS);
        checkHr(device.CreateCommittedResource(
                heapProps, windows.win32.graphics.direct3d12.D3D12_HEAP_FLAGS.D3D12_HEAP_FLAG_SHARED,
                resDesc, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COMMON,
                MemorySegment.NULL, windows.win32.graphics.direct3d12.ID3D12Resource.iid(),
                ppResource));
        return ppResource.get(ADDRESS, 0);
    }

    private static MemorySegment fillResourceDesc(Arena arena, int width, int height, int dxgiFormat) {
        MemorySegment resDesc = arena.allocate(
                windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.layout());
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Dimension(
                resDesc, windows.win32.graphics.direct3d12.D3D12_RESOURCE_DIMENSION.TEXTURE2D);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Alignment(resDesc, 0);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Width(resDesc, width);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Height(resDesc, height);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.DepthOrArraySize(resDesc, (short) 1);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.MipLevels(resDesc, (short) 1);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Format(
                resDesc, dxgiFormat);
        MemorySegment sampleDesc = arena.allocate(
                windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.layout());
        windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.Count(sampleDesc, 1);
        windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.Quality(sampleDesc, 0);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.SampleDesc(resDesc, sampleDesc);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Layout(
                resDesc, windows.win32.graphics.direct3d12.D3D12_TEXTURE_LAYOUT.UNKNOWN);
        windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Flags(
                resDesc, windows.win32.graphics.direct3d12.D3D12_RESOURCE_FLAGS.D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);
        return resDesc;
    }

    private static long queryAllocationSize(
            Arena arena,
            windows.win32.graphics.direct3d12.ID3D12Device device,
            MemorySegment resDesc) {
        // The GL import size must cover the real committed allocation. GetResourceAllocationInfo
        // cannot be called through FFM (struct-by-value ABI crashes the JVM) and the copyable
        // footprint can be smaller than the allocation (verified: 1920x991 copyable=7610880 is
        // rejected, tile-rounded 7864320 is accepted). For an R8G8B8A8 standard-swizzle texture
        // the allocation is 64KB tiles of 128x128 texels, so round the texel count up to tiles.
        long width = windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Width(resDesc);
        long height = windows.win32.graphics.direct3d12.D3D12_RESOURCE_DESC.Height(resDesc);
        long tilesX = (width + 127) / 128;
        long tilesY = (height + 127) / 128;
        return tilesX * tilesY * 65536L;
    }

    private static long createSharedHandle(
            Arena arena,
            windows.win32.graphics.direct3d12.ID3D12Device device,
            MemorySegment object) {
        MemorySegment ppHandle = arena.allocate(ADDRESS);
        checkHr(device.CreateSharedHandle(
                object, MemorySegment.NULL, 0x10000000 /* GENERIC_ALL */, MemorySegment.NULL, ppHandle));
        return ppHandle.get(JAVA_LONG, 0);
    }

    private static void checkHr(int hr) {
        if (hr < 0) {
            throw new IllegalStateException(
                    "D3D12/DXGI call failed with HRESULT 0x" + Integer.toHexString(hr));
        }
    }

    /**
     * Queries DXGI_FEATURE_PRESENT_ALLOW_TEARING on the factory. A failure or an
     * unsupported answer merely keeps the uncapped-present path disabled (vsync off then
     * falls back to the refresh-locked SyncInterval 0 behavior); it never fails setup.
     */
    private static boolean queryAllowTearing(windows.win32.graphics.dxgi.IDXGIFactory6 factory) {
        try (Arena temp = Arena.ofConfined()) {
            MemorySegment supported = temp.allocate(JAVA_INT);
            int hr = factory.CheckFeatureSupport(
                    windows.win32.graphics.dxgi.DXGI_FEATURE.PRESENT_ALLOW_TEARING,
                    supported, (int) JAVA_INT.byteSize());
            boolean result = hr >= 0 && supported.get(JAVA_INT, 0) != 0;
            io.homo.superresolution.common.SuperResolution.LOGGER.info(
                    "[D3D12] DXGI_FEATURE_PRESENT_ALLOW_TEARING={}", result);
            return result;
        } catch (Throwable throwable) {
            io.homo.superresolution.common.SuperResolution.LOGGER.debug(
                    "[D3D12] CheckFeatureSupport(ALLOW_TEARING) failed", throwable);
            return false;
        }
    }

    /** The flags the swap chain was created with; ResizeBuffers must pass the same value. */
    private static int swapchainFlags() {
        return allowTearingSupported
                ? windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_FLAG.ALLOW_TEARING : 0;
    }

    private static long queryOpenGlAdapterLuid() {
        try (MemoryStack stack = MemoryStack.stackPush()) {
            ByteBuffer luid = stack.calloc(EXTMemoryObjectWin32.GL_LUID_SIZE_EXT)
                    .order(ByteOrder.nativeOrder());
            EXTMemoryObject.glGetUnsignedBytevEXT(
                    EXTMemoryObjectWin32.GL_DEVICE_LUID_EXT, luid);
            long lowPart = Integer.toUnsignedLong(luid.getInt(0));
            long highPart = Integer.toUnsignedLong(luid.getInt(4));
            return lowPart | (highPart << 32);
        }
    }

    private static TextureDescription textureDescription(int width, int height, TextureFormat format, String label) {
        return TextureDescription.create()
                .type(TextureType.Texture2D)
                .width(width)
                .height(height)
                .format(format)
                .usages(TextureUsages.create().sampler().storage())
                .label(label)
                .build();
    }

    public void present(ITexture finalColor) {
        long captureValue = nextGlFence;
        // The GL work below (semaphore layout barriers + flipY compute) must not leak
        // GL state into the next frame: the Vulkan path wraps it in a GlState, and without
        // that the leaked texture-unit/program state makes font rendering sample the wrong
        // atlas (purple/black missing-texture stripes). The flip path only touches the
        // program, the active texture unit and texture bindings, so save just those
        // (~4 glGet instead of ~75): glGet is a driver sync point, and a STATE_ALL save
        // per frame adds CPU serialization that the Vulkan presentation does not have.
        long flipStateMask = GlState.STATE_PROGRAM | GlState.STATE_ACTIVE_TEXTURE | GlState.STATE_TEXTURE;
        try (GlState ignored = new GlState(flipStateMask)) {
            if (lastD3d12Signal > 0) {
                semaphore.waitFor(
                        lastD3d12Signal,
                        new int[]{
                                Math.toIntExact(captureGlTexture.handle()),
                                Math.toIntExact(depthGlTexture.handle()),
                                Math.toIntExact(mvGlTexture.handle()),
                                Math.toIntExact(hudlessGlTexture.handle())
                        },
                        new int[]{GL_LAYOUT_GENERAL_EXT, GL_LAYOUT_GENERAL_EXT,
                                GL_LAYOUT_GENERAL_EXT, GL_LAYOUT_GENERAL_EXT});
            }
            InteropResourcesConverter.flipY(finalColor, captureGlTexture);
            // Copy the captured Iris depth/motion vectors into the shared D3D12 textures
            // (same GL command stream, so one fence signal below covers all four).
            D3D12FrameGeneration.writeFrameInputs(this);
            semaphore.signal(
                    captureValue,
                    new int[]{
                            Math.toIntExact(captureGlTexture.handle()),
                            Math.toIntExact(depthGlTexture.handle()),
                            Math.toIntExact(mvGlTexture.handle()),
                            Math.toIntExact(hudlessGlTexture.handle())
                    },
                    new int[]{GL_LAYOUT_GENERAL_EXT, GL_LAYOUT_GENERAL_EXT,
                            GL_LAYOUT_GENERAL_EXT, GL_LAYOUT_GENERAL_EXT});
        }

        // Per-frame segments (barriers, copy locations, event) live in a confined arena:
        // allocating them on the context-lifetime arena accumulated memory every present.
        try (Arena frameArena = Arena.ofConfined()) {
            windows.win32.graphics.direct3d12.ID3D12CommandQueue queueIface =
                    windows.win32.graphics.direct3d12.ID3D12CommandQueue.wrap(queue);
            windows.win32.graphics.direct3d12.ID3D12Fence fenceIface =
                    windows.win32.graphics.direct3d12.ID3D12Fence.wrap(fence);
            windows.win32.graphics.dxgi.IDXGISwapChain3 swapchainIface =
                    windows.win32.graphics.dxgi.IDXGISwapChain3.wrap(swapchain);

            // Recycle the oldest command-allocator slot: wait only for the submit made
            // COMMAND_RING_DEPTH-1 frames ago (queue execution is FIFO, so that covers this
            // slot's previous commit). Never wait on the current frame — that zero-pipeline
            // stall is what starved the GPU below the Vulkan presentation.
            int ringSlot = acquireCommandRingSlot(fenceIface);

            // GPU-side ordering: queue waits for the GL flipY barrier+signal (shared fence)
            // before the copy below; this does not block the CPU.
            queueIface.Wait(fence, captureValue);

            checkHr(windows.win32.graphics.direct3d12.ID3D12CommandAllocator
                    .wrap(commandAllocators[ringSlot])
                    .Reset());
            checkHr(windows.win32.graphics.direct3d12.ID3D12GraphicsCommandList.wrap(commandList)
                    .Reset(commandAllocators[ringSlot], MemorySegment.NULL));

            int imageIndex = swapchainIface.GetCurrentBackBufferIndex();
            MemorySegment backBuffer = cachedBackBuffer(frameArena, swapchainIface, imageIndex);

            MemorySegment barriers = frameArena.allocate(
                    windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.layout(), 2);
            MemorySegment b0 = barriers;
            windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.Type(
                    b0, windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER_TYPE.TRANSITION);
            MemorySegment t0 = windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.Transition(b0);
            windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.pResource(t0, captureTexture);
            windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateBefore(
                    t0, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COMMON);
            windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateAfter(
                    t0, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COPY_SOURCE);
            MemorySegment b1 = barriers.asSlice(
                    windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.layout().byteSize());
            windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.Type(
                    b1, windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER_TYPE.TRANSITION);
            MemorySegment t1 = windows.win32.graphics.direct3d12.D3D12_RESOURCE_BARRIER.Transition(b1);
            windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.pResource(t1, backBuffer);
            windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateBefore(
                    t1, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COMMON);
            windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateAfter(
                    t1, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COPY_DEST);
            listIface().ResourceBarrier(2, barriers);

            MemorySegment dst = frameArena.allocate(
                    windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.layout());
            windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.pResource(dst, backBuffer);
            windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.Type(
                    dst, windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_TYPE.SUBRESOURCE_INDEX);
            windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.SubresourceIndex(dst, 0);
            MemorySegment src = frameArena.allocate(
                    windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.layout());
            windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.pResource(src, captureTexture);
            windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.Type(
                    src, windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_TYPE.SUBRESOURCE_INDEX);
            windows.win32.graphics.direct3d12.D3D12_TEXTURE_COPY_LOCATION.SubresourceIndex(src, 0);
            MemorySegment srcBox = frameArena.allocate(windows.win32.graphics.direct3d12.D3D12_BOX.layout());
            windows.win32.graphics.direct3d12.D3D12_BOX.left(srcBox, 0);
            windows.win32.graphics.direct3d12.D3D12_BOX.top(srcBox, 0);
            windows.win32.graphics.direct3d12.D3D12_BOX.front(srcBox, 0);
            windows.win32.graphics.direct3d12.D3D12_BOX.right(srcBox, width);
            windows.win32.graphics.direct3d12.D3D12_BOX.bottom(srcBox, height);
            windows.win32.graphics.direct3d12.D3D12_BOX.back(srcBox, 1);
            listIface().CopyTextureRegion(dst, 0, 0, 0, src, srcBox);

            windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateBefore(
                    t1, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COPY_DEST);
            // Return the back buffer to PRESENT state (not COMMON) before Present: the XeSS-FG
            // proxy tracks the back-buffer state and expects PRESENT for a presented buffer.
            windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateAfter(
                    t1, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_PRESENT);
            windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateBefore(
                    t0, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COPY_SOURCE);
            windows.win32.graphics.direct3d12.D3D12_RESOURCE_TRANSITION_BARRIER.StateAfter(
                    t0, windows.win32.graphics.direct3d12.D3D12_RESOURCE_STATES.D3D12_RESOURCE_STATE_COMMON);
            // Depth/mv are intentionally absent from these barriers: shared
            // (simultaneous-access) textures are never transitioned on this side; they sit
            // in COMMON for the SDK's Present-time lists (they decay at every ECL
            // completion, so an SRV declaration removes the device — 0x887a0001).
            listIface().ResourceBarrier(2, barriers);

            checkHr(listIface().Close());
            queueIface.ExecuteCommandLists(1, frameArena.allocateFrom(ADDRESS, commandList));

            // The copy above is FIFO-ordered after the GL flipY by the queue Wait, so no CPU
            // wait on the current frame's GPU work is needed (pacing comes from the flip-model
            // Present below).

            // Stamp the present latency markers. The Vulkan swapchain does this in its own
            // present path; the D3D12 presentation has no equivalent hook, so do it here for
            // the XeLL low-latency provider (present-start/end frame the swapchain Present).
            LowLatency.beginPresent();
            // If XeSS-FG took over the swap chain, tag constants and set the present id right
            // before Present so the proxy can generate interpolated frames.
            D3D12FrameGeneration.beforePresent();
            // Guard the XeLL/XeFG teardown-takeover cycle: beforePresent can release the
            // swap chain mid-present (releaseSwapchain sets the field to MemorySegment.NULL),
            // and when the takeover restore also fails the field stays NULL while
            // disableAfterFailure shuts the context down. Presenting through that NULL
            // handle dereferences address 0 in the IDXGISwapChain vtbl (AV 0xc0000005,
            // render thread, right after the libxess_fg.dll unload). Skip this frame's
            // Present; the fence signal below still advances the command ring, and
            // disableAfterFailure stops any further present.
            if (swapchain == null || swapchain.address() == 0L) {
                io.homo.superresolution.common.SuperResolution.LOGGER.warn(
                        "[D3D12] present skipped: swap chain released mid-frame (XeSS-FG/XeLL teardown)");
            } else {
                int presentResult = presentSwapchain(swapchain, vsync);
                if (presentResult != 0) {
                    io.homo.superresolution.common.SuperResolution.LOGGER.warn(
                            "[D3D12] present result=0x{}", Integer.toHexString(presentResult));
                    // The fence-ring fast path never polls the fence, so a removed device only
                    // surfaces here or in the next ring-slot wait: report it, stop frame
                    // generation and let the presentation feature fall back.
                    checkDeviceRemoved(fenceIface);
                } else {
                    io.homo.superresolution.common.SuperResolution.LOGGER.debug("[D3D12] present ok");
                }
            }
            LowLatency.endPresent();

            long signalValue = nextGlFence + 1;
            queueIface.Signal(fence, signalValue);
            lastD3d12Signal = signalValue;
            commandRingFences[ringSlot] = signalValue;
            nextGlFence += 2;
        }
    }

    /** The context's single resettable graphics command list. */
    private windows.win32.graphics.direct3d12.ID3D12GraphicsCommandList listIface() {
        return windows.win32.graphics.direct3d12.ID3D12GraphicsCommandList.wrap(commandList);
    }

    /**
     * Returns the swap-chain back buffer for {@code index}, cached (the cached reference is
     * held until the swap chain changes; the flip model guarantees at most bufferCount
     * distinct indices).
     */
    private MemorySegment cachedBackBuffer(
            Arena frameArena,
            windows.win32.graphics.dxgi.IDXGISwapChain3 swapchainIface,
            int index) {
        if (index >= 0 && index < backBuffers.length && backBuffers[index] != null
                && backBuffers[index].address() != 0L) {
            return backBuffers[index];
        }
        MemorySegment ppBackBuffer = frameArena.allocate(ADDRESS);
        checkHr(swapchainIface.GetBuffer(
                index, windows.win32.graphics.direct3d12.ID3D12Resource.iid(), ppBackBuffer));
        MemorySegment backBuffer = ppBackBuffer.get(ADDRESS, 0);
        // Store the pointer in the context-lifetime arena so the cache outlives the frame
        // arena; the cached COM reference is released with the cache.
        MemorySegment cached = arena.allocate(ADDRESS);
        cached.set(ADDRESS, 0, backBuffer);
        if (index >= 0 && index < backBuffers.length) {
            backBuffers[index] = cached.get(ADDRESS, 0);
        }
        return backBuffer;
    }

    /** Releases all cached back-buffer references (swap chain changed / shutdown). */
    private void releaseBackBuffers() {
        for (int i = 0; i < backBuffers.length; i++) {
            if (backBuffers[i] != null && backBuffers[i].address() != 0L) {
                windows.win32.graphics.direct3d12.ID3D12Resource.wrap(backBuffers[i]).Release();
                backBuffers[i] = MemorySegment.NULL;
            }
        }
    }

    /**
     * Advances the command-allocator ring and waits only for this slot's previous submit
     * (i.e. the submit from {@code COMMAND_RING_DEPTH-1} frames ago). Returns the slot to
     * use. A timeout or a removed device ({@code GetCompletedValue == UINT64_MAX}) throws
     * so the presentation feature can disable the D3D12 path instead of hanging.
     */
    private int acquireCommandRingSlot(windows.win32.graphics.direct3d12.ID3D12Fence fenceIface) {
        int slot = commandRingSlot;
        commandRingSlot = (commandRingSlot + 1) % COMMAND_RING_DEPTH;
        long pending = commandRingFences[slot];
        if (pending > 0L && fenceIface.GetCompletedValue() < pending) {
            waitOnFence(fenceIface, pending, "command ring slot " + slot);
        }
        return slot;
    }

    /**
     * Blocks until {@code fenceIface} reaches {@code value} (bounded ~2s) using the fence
     * completion event, falling back to polling when kernel32 cannot be bound. A timeout
     * throws (device removal when the fence reads as removed) instead of letting the next
     * present spin forever.
     */
    private void waitOnFence(windows.win32.graphics.direct3d12.ID3D12Fence fenceIface, long value, String what) {
        if (fenceIface.GetCompletedValue() >= value) {
            return;
        }
        if (CREATE_EVENT != null && WAIT_SINGLE_OBJECT != null && ensureFenceEvent()) {
            try {
                checkHr(fenceIface.SetEventOnCompletion(value, fenceEvent));
                // Bounded like the old polling loop; the auto-reset event covers retries.
                long deadline = System.nanoTime() + 2_000_000_000L;
                while (fenceIface.GetCompletedValue() < value
                        && System.nanoTime() < deadline) {
                    // remaining ms, at least 1
                    int remaining = (int) Math.max(1,
                            (deadline - System.nanoTime()) / 1_000_000L);
                    WAIT_SINGLE_OBJECT.invokeExact(fenceEvent, (int) remaining);
                }
            } catch (Throwable throwable) {
                io.homo.superresolution.common.SuperResolution.LOGGER.debug(
                        "[D3D12] fence event wait failed; polling", throwable);
                pollFence(fenceIface, value);
            }
        } else {
            pollFence(fenceIface, value);
        }
        long completedAfterWait = fenceIface.GetCompletedValue();
        if (completedAfterWait < value) {
            if (completedAfterWait == -1L) {
                // GetCompletedValue returns UINT64_MAX (reads as -1) when the device is
                // removed: log the driver's removal reason and stop frame generation.
                throwDeviceRemoved();
            }
            io.homo.superresolution.common.SuperResolution.LOGGER.warn(
                    "[D3D12] timed out waiting for {} (fence {} completed {})",
                    what, value, completedAfterWait);
            // A ring slot that never completes would stall present forever; treat it as
            // fatal so the presentation feature falls back to OpenGL/Vulkan safely.
            throw new IllegalStateException("D3D12 fence wait timed out: " + what);
        }
    }

    private void pollFence(
            windows.win32.graphics.direct3d12.ID3D12Fence fenceIface, long value) {
        for (int i = 0; i < 2000; i++) {
            if (fenceIface.GetCompletedValue() >= value) {
                return;
            }
            try {
                Thread.sleep(1);
            } catch (InterruptedException interrupted) {
                Thread.currentThread().interrupt();
                return;
            }
        }
    }

    /** Reports and throws on device removal; called where the fast path would miss it. */
    private void checkDeviceRemoved(windows.win32.graphics.direct3d12.ID3D12Fence fenceIface) {
        if (fenceIface.GetCompletedValue() == -1L) {
            throwDeviceRemoved();
        }
    }

    /**
     * Whether the D3D12 device is already removed (GetDeviceRemovedReason != S_OK). Used
     * as a preflight before handing the window to the XeSS-FG SDK: initializing on a dead
     * device guarantees the failure restore fails too (CreateSwapChainForHwnd returns
     * DXGI_ERROR_DEVICE_REMOVED) and cascades into the frozen-window fallback.
     */
    public boolean isDeviceRemoved() {
        try {
            return windows.win32.graphics.direct3d12.ID3D12Device.wrap(device)
                    .GetDeviceRemovedReason() != 0;
        } catch (Throwable throwable) {
            return false;
        }
    }

    private void throwDeviceRemoved() {
        int removalReason = windows.win32.graphics.direct3d12.ID3D12Device.wrap(device)
                .GetDeviceRemovedReason();
        D3D12FrameGeneration.onDeviceRemoved(removalReason);
        throw new IllegalStateException("D3D12 device removed (reason 0x"
                + Integer.toHexString(removalReason) + ")");
    }

    private boolean ensureFenceEvent() {
        if (fenceEvent.address() != 0L) {
            return true;
        }
        try {
            MemorySegment event = (MemorySegment) CREATE_EVENT.invokeExact(
                    MemorySegment.NULL, 0, 0, MemorySegment.NULL);
            if (event.address() != 0L) {
                fenceEvent = event;
                return true;
            }
        } catch (Throwable throwable) {
            io.homo.superresolution.common.SuperResolution.LOGGER.debug(
                    "[D3D12] CreateEventW failed", throwable);
        }
        return false;
    }

    /** Clears the cached Present slot (e.g. when the XeSS-FG proxy is torn down). */
    public void resetPresentSlot() {
        cachedXefgPresentFn = 0L;
    }

    /**
     * Captures the current swap chain's Present vtable slot (8) once. Called on XeSS-FG
     * takeover: the proxy nulls the slot after the first Present, so the captured function
     * pointer is what keeps later presents working.
     */
    public void capturePresentSlot() {
        try {
            MemorySegment vtable = swapchain.reinterpret(ADDRESS.byteSize()).get(ADDRESS, 0);
            long slot = vtable.reinterpret(ADDRESS.byteSize() * 12)
                    .get(ADDRESS, ADDRESS.byteSize() * 8).address();
            if (slot != 0L) {
                cachedXefgPresentFn = slot;
                io.homo.superresolution.common.SuperResolution.LOGGER.info(
                        "[D3D12] captured XeSS-FG Present slot=0x{}", Long.toHexString(slot));
            } else {
                io.homo.superresolution.common.SuperResolution.LOGGER.warn(
                        "[D3D12] captured Present slot is NULL");
            }
        } catch (Throwable throwable) {
            io.homo.superresolution.common.SuperResolution.LOGGER.warn(
                    "[D3D12] capture Present slot failed", throwable);
        }
    }

    /**
     * Presents through the current swap chain. When XeSS-FG took over, the proxy nulls its
     * Present vtable slot after the first Present, so a cached function pointer captured on
     * takeover is used instead of re-reading the vtable each frame.
     *
     * <p>While the proxy is active the tear flag is never passed to the Present: the
     * proxy's chain can lack DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING even when the takeover
     * description asked for it (the backend's runtime feature query can fail while the
     * presentation's own query succeeded), and Present(0, ALLOW_TEARING) on such a chain
     * not only fails itself — it also poisons the SDK's interpolated-frame presents,
     * which then fail with DXGI_ERROR_INVALID_CALL on every frame and freeze the screen.
     * The plain (non-proxy) chain keeps the tear flag when tearing is supported; a
     * rejected tear flag there degrades to immediate Present once for the session.
     */
    private static final int DXGI_ERROR_INVALID_CALL = 0x887A0001;

    private static volatile boolean tearingDegraded;

    private static int presentSwapchain(MemorySegment swapchain, boolean vsync) {
        if (swapchain == null || swapchain.address() == 0L) {
            // Defensive: never walk the vtbl of a released swap chain (AV at 0x0).
            return 0;
        }
        int syncInterval = vsync ? 1 : 0;
        // DXGI_PRESENT_ALLOW_TEARING is only legal with SyncInterval 0 on a swap chain
        // created with DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING. The XeSS-FG proxy chain can
        // end up without the flag even when the takeover description asked for it (the
        // runtime feature query inside the backend may fail), and handing the tear flag
        // to the proxy's Present poisons the SDK: it rejects the Present AND every
        // interpolated-frame Present it issues afterwards fails with 0x887A0001, freezing
        // the screen. While the proxy is active, never pass the tear flag — the proxy
        // presents the interpolated frames itself and owns their pacing.
        int presentFlags = 0;
        if (cachedXefgPresentFn == 0L && !vsync && allowTearingSupported) {
            presentFlags = windows.win32.graphics.dxgi.DXGI_PRESENT.ALLOW_TEARING;
        }
        int result = doPresent(swapchain, syncInterval, presentFlags);
        if (result == DXGI_ERROR_INVALID_CALL && presentFlags != 0) {
            if (!tearingDegraded) {
                tearingDegraded = true;
                io.homo.superresolution.common.SuperResolution.LOGGER.warn(
                        "[D3D12] Present(0, ALLOW_TEARING) rejected by the swap chain"
                                + " (0x887A0001, proxy chain without the tear flag);"
                                + " degrading to plain immediate Present for this session");
            }
            result = doPresent(swapchain, syncInterval, 0);
        }
        return result;
    }

    private static int doPresent(MemorySegment swapchain, int syncInterval, int presentFlags) {
        long fn = cachedXefgPresentFn;
        if (fn == 0L) {
            // No XeSS-FG takeover yet: present through the plain vtable like before.
            return windows.win32.graphics.dxgi.IDXGISwapChain3.wrap(swapchain)
                    .Present(syncInterval, presentFlags);
        }
        try {
            return (int) PRESENT_DOWN.invokeExact(
                    MemorySegment.ofAddress(fn), swapchain, syncInterval, presentFlags);
        } catch (Throwable throwable) {
            throw new RuntimeException("D3D12 present via cached XeSS-FG slot failed", throwable);
        }
    }

    private static MemorySegment buildSwapchainDesc(Arena arena, int width, int height) {
        MemorySegment scDesc = arena.allocate(
                windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.layout());
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.Width(scDesc, width);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.Height(scDesc, height);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.Format(
                scDesc, windows.win32.graphics.dxgi.common.DXGI_FORMAT.R8G8B8A8_UNORM);
        MemorySegment sampleDesc = arena.allocate(
                windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.layout());
        windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.Count(sampleDesc, 1);
        windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.Quality(sampleDesc, 0);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.SampleDesc(scDesc, sampleDesc);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.BufferUsage(scDesc, 0x20);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.BufferCount(scDesc, 3);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.SwapEffect(
                scDesc, windows.win32.graphics.dxgi.DXGI_SWAP_EFFECT.FLIP_SEQUENTIAL);
        windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC1.Flags(scDesc, swapchainFlags());
        return scDesc;
    }

    public void resize(int newWidth, int newHeight) {
        if (newWidth == width && newHeight == height) {
            return;
        }
        // FLIP model: ResizeBuffers returns DXGI_ERROR_NOT_CURRENTLY_AVAILABLE while the
        // previous frame's back buffer is still referenced by in-flight GPU work, and the
        // DWM compositor may hold it a while longer after the GPU is idle. Wait and retry
        // over a longer window, then fall back to recreating the swap chain like the
        // reference Vulkan surface does.
        waitForGpu();
        // ResizeBuffers re-creates the back buffers, so cached references must go first.
        releaseBackBuffers();
        int lastHr = 0;
        if (swapchain == null || swapchain.address() == 0L) {
            // The swap chain was already released (a XeSS-FG takeover release defers the
            // restore to this resize so the chain is only built once, at the new size).
            // Recreate it instead of resizing through a dangling NULL pointer — wrapping
            // the NULL segment and calling ResizeBuffers1 dereferences address 0.
            recreateSwapchain(newWidth, newHeight);
        } else {
            windows.win32.graphics.dxgi.IDXGISwapChain3 swapchainIface =
                    windows.win32.graphics.dxgi.IDXGISwapChain3.wrap(swapchain);
            for (int retry = 0; retry < 8; retry++) {
                if (retry > 0) {
                    try {
                        Thread.sleep(32L * retry);
                    } catch (InterruptedException interrupted) {
                        Thread.currentThread().interrupt();
                        break;
                    }
                    waitForGpu();
                }
                lastHr = swapchainIface.ResizeBuffers1(3, newWidth, newHeight,
                        windows.win32.graphics.dxgi.common.DXGI_FORMAT.R8G8B8A8_UNORM,
                        swapchainFlags(),
                        MemorySegment.NULL, MemorySegment.NULL);
                if (lastHr >= 0) {
                    break;
                }
            }
        }
        if (lastHr < 0) {
            try {
                recreateSwapchain(newWidth, newHeight);
            } catch (Throwable throwable) {
                // recreateSwapchain released the old swap chain before attempting to create
                // the replacement, so the swapchain field now dangles. Re-throw so the caller
                // skips present and disables D3D12 presentation instead of presenting through
                // a freed swap chain (use-after-free crash).
                io.homo.superresolution.common.SuperResolution.LOGGER.error(
                        "[D3D12] ResizeBuffers to {}x{} failed 0x{} and recreate failed; "
                                + "disabling D3D12 presentation",
                        newWidth, newHeight, Integer.toHexString(lastHr), throwable);
                throw throwable;
            }
        }
        // The back buffer changed size, so the capture texture must be rebuilt to match;
        // otherwise present copies a stale-sized source into the new back buffer.
        recreateCaptureResources(newWidth, newHeight);
        width = newWidth;
        height = newHeight;
    }

    /**
     * Resizes the CURRENT swap chain in place — including the XeSS-FG proxy chain — and
     * returns the final HRESULT ({@code >= 0} on success). The swap chain object itself
     * is kept, so an active XeSS-FG takeover survives the resize.
     *
     * <p>The buffer count/format/flags come from {@code GetDesc} instead of our own
     * preferred values: DXGI rejects a ResizeBuffers whose parameters do not match the
     * chain's creation desc (E_INVALIDARG — observed when resizing the SDK's tearless
     * proxy chain with our ALLOW_TEARING flag), and only the creation desc is guaranteed
     * to be accepted. The XeSS-FG SDK is built for this: it interposes Present on the
     * proxy and re-queries the back buffers, and the header exposes
     * {@code UpdateExternalHeapOnResize} precisely because in-place resizes are
     * supported.</p>
     */
    public int resizeSwapchainInPlace(int newWidth, int newHeight) {
        if (swapchain == null || swapchain.address() == 0L) {
            return 0x80004005; // E_FAIL: nothing to resize (caller falls back)
        }
        waitForGpu();
        // ResizeBuffers re-creates the back buffers, so cached references must go first.
        releaseBackBuffers();
        int lastHr = 0;
        int bufferCount = 3;
        int format = windows.win32.graphics.dxgi.common.DXGI_FORMAT.R8G8B8A8_UNORM;
        int flags = 0;
        try (Arena frameArena = Arena.ofConfined()) {
            MemorySegment desc = frameArena.allocate(
                    windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC.layout());
            checkHr(windows.win32.graphics.dxgi.IDXGISwapChain.wrap(swapchain).GetDesc(desc));
            bufferCount = windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC.BufferCount(desc);
            format = windows.win32.graphics.dxgi.common.DXGI_MODE_DESC.Format(
                    windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC.BufferDesc(desc));
            flags = windows.win32.graphics.dxgi.DXGI_SWAP_CHAIN_DESC.Flags(desc);
        } catch (Throwable throwable) {
            // Desc query failed: fall through with our defaults and let ResizeBuffers
            // verdict decide (the caller releases the takeover on failure).
            io.homo.superresolution.common.SuperResolution.LOGGER.debug(
                    "[D3D12] swapchain GetDesc failed during in-place resize", throwable);
        }
        windows.win32.graphics.dxgi.IDXGISwapChain3 swapchainIface =
                windows.win32.graphics.dxgi.IDXGISwapChain3.wrap(swapchain);
        for (int retry = 0; retry < 8; retry++) {
            if (retry > 0) {
                try {
                    Thread.sleep(32L * retry);
                } catch (InterruptedException interrupted) {
                    Thread.currentThread().interrupt();
                    break;
                }
                waitForGpu();
            }
            lastHr = swapchainIface.ResizeBuffers1(bufferCount, newWidth, newHeight,
                    format, flags, MemorySegment.NULL, MemorySegment.NULL);
            if (lastHr >= 0) {
                break;
            }
        }
        if (lastHr >= 0) {
            recreateCaptureResources(newWidth, newHeight);
            width = newWidth;
            height = newHeight;
        }
        return lastHr;
    }

    /** Releases the swap chain so the XeSS-FG SDK can create its own on the window. */
    public void releaseSwapchain() {
        releaseBackBuffers();
        if (swapchain != null && swapchain.address() != 0L) {
            windows.win32.graphics.dxgi.IDXGISwapChain3.wrap(swapchain).Release();
            swapchain = MemorySegment.NULL;
        }
    }

    /** Recreates the swap chain (used to restore it if XeSS-FG initialization fails). */
    public void recreateSwapchain(int newWidth, int newHeight) {
        // A window may only own one flip-model swap chain, so release the old one
        // before creating a replacement (otherwise CreateSwapChainForHwnd fails).
        releaseBackBuffers();
        if (swapchain != null && swapchain.address() != 0) {
            windows.win32.graphics.dxgi.IDXGISwapChain3.wrap(swapchain).Release();
        }
        MemorySegment ppFactory = arena.allocate(ADDRESS);
        checkHr(windows.win32.graphics.dxgi.Apis.CreateDXGIFactory2(
                0, windows.win32.graphics.dxgi.IDXGIFactory6.iid(), ppFactory));
        windows.win32.graphics.dxgi.IDXGIFactory6 factory =
                windows.win32.graphics.dxgi.IDXGIFactory6.wrap(ppFactory.get(ADDRESS, 0));
        this.factory = ppFactory.get(ADDRESS, 0);
        // The flags written into the new desc must match what Present/ResizeBuffers will
        // use, so re-query tearing support for the new factory before building the desc.
        allowTearingSupported = queryAllowTearing(factory);
        MemorySegment scDesc = buildSwapchainDesc(arena, newWidth, newHeight);
        MemorySegment ppNew = arena.allocate(ADDRESS);
        checkHr(factory.CreateSwapChainForHwnd(
                queue, MemorySegment.ofAddress(hwnd), scDesc, MemorySegment.NULL,
                MemorySegment.NULL, ppNew));
        this.swapchain = ppNew.get(ADDRESS, 0);
        io.homo.superresolution.common.SuperResolution.LOGGER.info(
                "[D3D12] swapchain recreated to {}x{}", newWidth, newHeight);
    }

    private void recreateCaptureResources(int newWidth, int newHeight) {
        // Build the new textures fully before touching the old ones, so a failure
        // here leaves the previous ones intact instead of leaving a null that would
        // NPE in present() and crash the game.
        windows.win32.graphics.direct3d12.ID3D12Device deviceIface =
                windows.win32.graphics.direct3d12.ID3D12Device.wrap(device);

        MemorySegment captureDesc = fillResourceDesc(
                arena, newWidth, newHeight, windows.win32.graphics.dxgi.common.DXGI_FORMAT.R8G8B8A8_UNORM);
        MemorySegment newCaptureTexture = createCaptureTexture(arena, deviceIface, captureDesc);
        long captureHandle = createSharedHandle(arena, deviceIface, newCaptureTexture);
        long newSize = queryAllocationSize(arena, deviceIface, captureDesc);
        GlD3D12ImportableTexture2D newCaptureGlTexture = new GlD3D12ImportableTexture2D(
                new D3D12InteropContext.Resource(0, 0, captureHandle, newSize,
                        textureDescription(newWidth, newHeight, TextureFormat.RGBA8, "D3D12PresentationCapture"),
                        SRSurfaceFormat.R8G8B8A8_UNORM));
        if (captureGlTexture != null) {
            captureGlTexture.destroy();
        }
        this.captureTexture = newCaptureTexture;
        this.captureAllocationSize = newSize;
        this.captureGlTexture = newCaptureGlTexture;

        MemorySegment hudlessDesc = fillResourceDesc(
                arena, newWidth, newHeight, windows.win32.graphics.dxgi.common.DXGI_FORMAT.R8G8B8A8_UNORM);
        MemorySegment newHudlessTexture = createCaptureTexture(arena, deviceIface, hudlessDesc);
        long hudlessHandle = createSharedHandle(arena, deviceIface, newHudlessTexture);
        long hudlessSize = queryAllocationSize(arena, deviceIface, hudlessDesc);
        GlD3D12ImportableTexture2D newHudlessGlTexture = new GlD3D12ImportableTexture2D(
                new D3D12InteropContext.Resource(0, 0, hudlessHandle, hudlessSize,
                        textureDescription(newWidth, newHeight, TextureFormat.RGBA8, "D3D12PresentationHudless"),
                        SRSurfaceFormat.R8G8B8A8_UNORM));
        if (hudlessGlTexture != null) {
            hudlessGlTexture.destroy();
        }
        this.hudlessTexture = newHudlessTexture;
        this.hudlessAllocationSize = hudlessSize;
        this.hudlessGlTexture = newHudlessGlTexture;

        // The depth/motion-vector textures no longer follow the presentation extent: they
        // are managed by ensureFrameInputResources at the frame inputs' native dispatch
        // resolution and survive a window resize until the next dispatch says otherwise.
    }

    /**
     * Rebuilds the shared depth/motion-vector textures at the frame inputs' native
     * (dispatch) resolution. XeSS-FG receives them tagged at this extent as low-res
     * motion vectors (the documented default) and upsamples/dilates internally — the
     * previous behavior blitted them up to the presentation extent, which both cost a
     * full-resolution copy per frame and fed the SDK pre-blurred velocities. The two
     * inputs must share one extent (SDK constraint), so callers fall back to the
     * presentation extent when the dispatch textures disagree.
     */
    public void ensureFrameInputResources(int newWidth, int newHeight) {
        if (newWidth <= 0 || newHeight <= 0) {
            return;
        }
        if (frameInputWidth == newWidth && frameInputHeight == newHeight
                && depthTexture != null && mvTexture != null) {
            return;
        }
        // The SDK interpolates from these textures on the presentation queue; wait for
        // the last submitted frame before the old resources are destroyed. Size changes
        // are rare (render-scale/pack switches), so the stall is acceptable.
        waitForGpu();
        recreateFrameInputResources(newWidth, newHeight);
        io.homo.superresolution.common.SuperResolution.LOGGER.info(
                "[D3D12] frame-input textures rebuilt at {}x{}", newWidth, newHeight);
    }

    private void recreateFrameInputResources(int newWidth, int newHeight) {
        windows.win32.graphics.direct3d12.ID3D12Device deviceIface =
                windows.win32.graphics.direct3d12.ID3D12Device.wrap(device);

        MemorySegment depthDesc = fillResourceDesc(
                arena, newWidth, newHeight, windows.win32.graphics.dxgi.common.DXGI_FORMAT.R32_FLOAT);
        MemorySegment newDepthTexture = createCaptureTexture(arena, deviceIface, depthDesc);
        long depthHandle = createSharedHandle(arena, deviceIface, newDepthTexture);
        long depthSize = queryAllocationSize(arena, deviceIface, depthDesc);
        GlD3D12ImportableTexture2D newDepthGlTexture = new GlD3D12ImportableTexture2D(
                new D3D12InteropContext.Resource(0, 0, depthHandle, depthSize,
                        textureDescription(newWidth, newHeight, TextureFormat.R32F, "D3D12PresentationDepth"),
                        SRSurfaceFormat.R32_FLOAT));

        MemorySegment mvDesc = fillResourceDesc(
                arena, newWidth, newHeight, windows.win32.graphics.dxgi.common.DXGI_FORMAT.R16G16_FLOAT);
        MemorySegment newMvTexture = createCaptureTexture(arena, deviceIface, mvDesc);
        long mvHandle = createSharedHandle(arena, deviceIface, newMvTexture);
        long mvSize = queryAllocationSize(arena, deviceIface, mvDesc);
        GlD3D12ImportableTexture2D newMvGlTexture = new GlD3D12ImportableTexture2D(
                new D3D12InteropContext.Resource(0, 0, mvHandle, mvSize,
                        textureDescription(newWidth, newHeight, TextureFormat.RG16F, "D3D12PresentationMotionVector"),
                        SRSurfaceFormat.R16G16_FLOAT));

        if (depthGlTexture != null) {
            depthGlTexture.destroy();
        }
        if (mvGlTexture != null) {
            mvGlTexture.destroy();
        }
        // The GL import dropped its reference; release this side's COM reference too
        // (the resize path previously leaked the old committed resources).
        if (depthTexture != null && depthTexture.address() != 0L) {
            windows.win32.graphics.direct3d12.ID3D12Resource.wrap(depthTexture).Release();
        }
        if (mvTexture != null && mvTexture.address() != 0L) {
            windows.win32.graphics.direct3d12.ID3D12Resource.wrap(mvTexture).Release();
        }
        this.depthTexture = newDepthTexture;
        this.depthAllocationSize = depthSize;
        this.depthGlTexture = newDepthGlTexture;
        this.mvTexture = newMvTexture;
        this.mvAllocationSize = mvSize;
        this.mvGlTexture = newMvGlTexture;
        this.frameInputWidth = newWidth;
        this.frameInputHeight = newHeight;
    }

    /**
     * Blocks until the presentation queue has completed all submitted work (bounded by a
     * 2s poll). Public because the XeSS-FG takeover must hand the window to the SDK only
     * on an idle queue: re-running {@code xefgSwapChainD3D12InitFromSwapChainDesc} while
     * our command queue still has in-flight work hangs the device (observed
     * {@code DXGI_ERROR_DEVICE_HUNG 0x887a0006} right after a resize released the proxy
     * and the next frame re-took the swap chain).
     */
    public void waitForGpu() {
        if (lastD3d12Signal <= 0) {
            return;
        }
        windows.win32.graphics.direct3d12.ID3D12Fence fenceIface =
                windows.win32.graphics.direct3d12.ID3D12Fence.wrap(fence);
        for (int i = 0; i < 2000; i++) {
            if (fenceIface.GetCompletedValue() >= lastD3d12Signal) {
                return;
            }
            try {
                Thread.sleep(1);
            } catch (InterruptedException interrupted) {
                Thread.currentThread().interrupt();
                return;
            }
        }
        io.homo.superresolution.common.SuperResolution.LOGGER.warn(
                "[D3D12] timed out waiting for GPU idle before resize");
    }

    public int width() {
        return width;
    }

    public int height() {
        return height;
    }

    /** The FFM D3D12 device segment, used by the XeLL low-latency provider. */
    public MemorySegment device() {
        return device;
    }

    /** The FFM D3D12 command queue, used by the XeSS-FG backend. */
    public MemorySegment queue() {
        return queue;
    }

    /** The Win32 window handle the swap chain is attached to. */
    public long hwnd() {
        return hwnd;
    }

    /** The current DXGI swap chain (may be a XeSS-FG proxy swap chain). */
    public MemorySegment swapchain() {
        return swapchain;
    }

    /** The DXGI factory used to create the swap chain, for the XeSS-FG backend. */
    public MemorySegment factory() {
        return factory;
    }

    /** Replaces the swap chain, e.g. with the XeSS-FG proxy swap chain. */
    public void setSwapchain(MemorySegment swapchain) {
        releaseBackBuffers();
        this.swapchain = swapchain;
    }

    /** The D3D12 depth resource (R32_FLOAT), tagged to XeSS-FG each present. */
    public MemorySegment depthTexture() {
        return depthTexture;
    }

    /** The D3D12 motion-vector resource (R16G16_FLOAT), tagged to XeSS-FG each present. */
    public MemorySegment mvTexture() {
        return mvTexture;
    }

    /** GL view of the depth resource, for writing the frame's depth each present. */
    public GlD3D12ImportableTexture2D depthGlTexture() {
        return depthGlTexture;
    }

    /** GL view of the motion-vector resource, for writing the frame's MV each present. */
    public GlD3D12ImportableTexture2D mvGlTexture() {
        return mvGlTexture;
    }

    /** The D3D12 HUD-less color resource (R8G8B8A8), tagged to XeSS-FG each present. */
    public MemorySegment hudlessTexture() {
        return hudlessTexture;
    }

    /** GL view of the HUD-less resource, for writing the frame's pre-UI color each present. */
    public GlD3D12ImportableTexture2D hudlessGlTexture() {
        return hudlessGlTexture;
    }

    /** Matches the OpenGL vsync setting: flip-model Present uses syncInterval 1 (wait for
     * vsync) when vsync is on, 0 (immediate) otherwise. */
    public void setVsync(boolean enabled) {
        this.vsync = enabled;
    }

    @Override
    public void close() {
        releaseBackBuffers();
        if (fenceEvent.address() != 0L && CLOSE_HANDLE != null) {
            try {
                CLOSE_HANDLE.invokeExact(fenceEvent);
            } catch (Throwable throwable) {
                io.homo.superresolution.common.SuperResolution.LOGGER.debug(
                        "[D3D12] fence event close failed", throwable);
            }
            fenceEvent = MemorySegment.NULL;
        }
        arena.close();
    }

    public static boolean isNativeAvailable() {
        // The FFM bindings are compiled in; D3D12 presentation only works on Windows.
        return io.homo.superresolution.api.platform.Platform.currentPlatform.getOS().type
                == io.homo.superresolution.api.platform.OperatingSystemType.WINDOWS;
    }
}
#else
public final class D3D12PresentationContext {
}
#endif
