org.gradle.jvmargs=-Xmx16G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
group=io.homo.SuperResolution
projectName=super_resolution
manifold_version=2026.1.6
#??/configs???/
minecraft_version_config=1.21.11
mod_version=0.9.0-alpha.1
mod_id=super_resolution

is_dev=true
is_vulkan=false
enable_auto_download=true
use_debug_lib=true

